export const arrayFilledButton = [
	{
		bg: 'primary',
		borderColor: 'primary',
		label: 'primary',
		borderRadius: 'md',
		size: 'md',
		color: 'light',
	},
	{
		bg: 'secondary',
		borderColor: 'secondary',
		label: 'secondary',
		borderRadius: 'md',
		size: 'md',
		color: 'light',
	},
	{
		bg: 'danger',
		borderColor: 'danger',
		label: 'danger',
		borderRadius: 'md',
		size: 'md',
		color: 'light',
	},
	{
		bg: 'warning',
		borderColor: 'warning',
		label: 'warning',
		borderRadius: 'md',
		size: 'md',
		color: 'light',
	},
	{
		bg: 'success',
		borderColor: 'success',
		label: 'success',
		borderRadius: 'md',
		size: 'md',
		color: 'light',
	},
];
export const arrayBorderedButton = [
	{
		borderColor: 'primary',
		label: 'primary',
		borderRadius: 'md',
		size: 'md',
		color: 'primary',
	},
	{
		borderColor: 'secondary',
		label: 'secondary',
		borderRadius: 'md',
		size: 'md',
		color: 'secondary',
	},
	{
		borderColor: 'danger',
		label: 'danger',
		borderRadius: 'md',
		size: 'md',
		color: 'danger',
	},
	{
		borderColor: 'warning',
		label: 'warning',
		borderRadius: 'md',
		size: 'md',
		color: 'warning',
	},
	{
		borderColor: 'success',
		label: 'success',
		borderRadius: 'md',
		size: 'md',
		color: 'success',
	},
];
